(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
SetDirectory[NotebookDirectory[]]
ClearAll[t]


(* ::Input::Initialization:: *)
initialConds={lake1Vol[0]==1000(*,lake1inflow[t_/;t\[LessEqual]0]\[Equal]10*)};
behaviors={lake1Vol'[t]==lake1inflow[t]-lake1outflow[t]};


(* ::Input::Initialization:: *)
lakeEqns={lake1Height[t]==lake1Vol[t]/100};


(* ::Input::Initialization:: *)
inflows={lake1inflow[t]==10+3Sin[t*2 Pi / 365]};


(* ::Input::Initialization:: *)
damPolicy={lake1outflow[t]==lake1Height[t]};



